import { end } from "./lib/javaInit";
import Color = require("./lib/Color");
import Matrix = require("./lib/Matrix");
import PDDocument = require("./lib/PDDocument");
import PDDocumentInformation = require("./lib/PDDocumentInformation");
import PDPage = require("./lib/PDPage");
import PDPageContentStream = require("./lib/PDPageContentStream");
import PDPageTree = require("./lib/PDPageTree");
import PDRectangle = require("./lib/PDRectangle");
import PDType1Font = require("./lib/PDType1Font");
import Vector = require("./lib/Vector");
export { end as Close, Color, Matrix, PDDocument, PDDocumentInformation, PDPage, PDPageContentStream, PDPageTree, PDRectangle, PDType1Font, Vector };
