# name: "CodeQL"

# on: [push]
# jobs:
#     analyze:
#         name: Analyze

#         permissions:
#             actions: read
#             contents: read
#             security-events: write

#         strategy:
#             fail-fast: false
#             matrix:
#                 language: ["javascript"]
#         runs-on: ubuntu-latest

#         steps:
#             - name: Checkout repository
#               uses: actions/checkout@v3

#             - name: Initialize CodeQL
#               uses: github/codeql-action/init@v2
#               with:
#                   languages: ${{ matrix.language }}

#             - name: Perform CodeQL Analysis
#               uses: github/codeql-action/analyze@v2

#             - name: Test
#               run: |
#                   npm ci
#                   npm run test
