name: "Test"

on: [push]
jobs:
    analyze:
        name: Test

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                java: [17]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: "adopt"
                  java-version: ${{ matrix.java }}
            - uses: actions/setup-node@v3
            - name: Test
              run: |
                  npm ci
                  npm run test
